language: r

jobs:
 - os: linux
   r: oldrel
 - os: linux
   r: release
 - os: linux
   r: devel
 - os: osx
   r: oldrel
 - os: osx
   r: release

warnings_are_errors: true

cache: packages

before_install:
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
     sed -i "1iexport PATH=$(dirname $(which R)):$(pwd)/tests/bin:\$PATH" ~/.bashrc;
     sed -i "2iexport R_LIBS_USER=$R_LIBS_USER" ~/.bashrc;
     sed -i "3iexport R_LIBS_SITE=$R_LIBS_SITE" ~/.bashrc;
     source ~/.bashrc;
     sudo apt-get install libzmq3-dev;
   elif [ "$TRAVIS_OS_NAME" = "osx" ]; then
     brew update;
     brew install zeromq;
   fi
 - ssh-keygen -t rsa -f ~/.ssh/id_rsa -N "" -q
 - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
 - ssh-keyscan -t rsa 127.0.0.1 >> ~/.ssh/known_hosts
 - echo "Host 127.0.0.1
    IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
 - echo "$(hostname) 127.0.0.1" >> ~/.hosts

before_script:
 - pwd
 - cat ~/.bashrc
 - which R
 - which sbatch || true
 - ssh 127.0.0.1 'which R; which sbatch; echo $PATH' || true
 - ssh 127.0.0.1 'R --no-save --no-restore -e ".libPaths()"' || true

script:
 - R CMD build .
 - R CMD INSTALL *.tar.gz
 - R --no-save --no-restore -e "message(clustermq:::qsys_default)" > /dev/null
 - ssh 127.0.0.1 'R --no-save --no-restore -e "message(clustermq:::qsys_default)" > /dev/null' || true
 - make test
 - timeout 300 make check
# - timeout 120 R CMD check --as-cran *.tar.gz

after_failure:
 - cat ~/*.log
 - cat ~/worker.log || true
 - cat ~/ssh_proxy.log || true
 - cat clustermq.Rcheck/tests/* || true
